server:
  port: 8003

spring:
  application:
    name: post-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://192.168.192.2:30088} # VPN

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev