server:
  port: 8003

spring:
  application:
    name: post-service

  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update # update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

minio:
  url: http://localhost:9000
  access-key: ROOTUSER
  secret-key: CHANGEME123
  bucket: images