apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  selector:
    app: post-service
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      nodePort: 30083
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: dummy
          image: alpine
          command: ["sleep", "3600"]